apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    backstage.io/kubernetes-id: lighthouse-audit
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: devexp-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: addon-http-application-routing
  name: lighthouse-audit
  namespace: dx-poc
spec:
  rules:
  - host: lighthouse-audit.3b709546ecd14fc68eab.eastus.aksapp.io
    http:
      paths:
      - path: /
        backend:
          serviceName: lighthouse-audit
          servicePort: 8080
  tls:
    - hosts:
      - lighthouse-audit.3b709546ecd14fc68eab.eastus.aksapp.io
      secretName: lighthouse-audit-tls-secret-poc